name: yaru-dark-theme-toggle
version: '1.0'
summary: Yaru Dark Theme Toggle
description: Toggles between Yaru and Yaru-dark

grade: stable  
confinement: classic 
base: core18

parts:
  gnome-shell-extension-yaru-dark-theme-toggle:
    plugin: dump
    source: yarudarkthemetoggle@feichtmeier.me/
