#!/usr/bin/env bash

mkdir -p /usr/share/gnome-shell/extensions

ln -s /snap/gnome-shell-extension-yaru-dark-theme-toggle/current /usr/share/gnome-shell/extensions/yarudarkthemetoggle@feichtmeier.me

gnome-shell-extension-tool -e yarudarkthemetoggle@feichtmeier.me
